### ISSUE TITLE
selectable output folder for single file minifications

### ISSUE THREAD

**Issue by mherzhoff** [purple-force/css-minify#6]
Hey @purple-force,
it would be awesome if you could enhance the script by let the user choose an optional output folder for single file transformations (as done for folder minifications).
Should be done by a small change of file `bin/css-minify.js` on [line 29](https://github.com/purple-force/css-minify/blob/5cb8d2d6303cd3073671b2b25057ee2190481d88/bin/css-minify.js#L29):
`resolveFile(path.join(process.cwd(), file), out);`

**Comment by purple-force** [comment]
css-minify@2.0.0
